food/urls.py
from django.urls import path
from food.views import *
app_name='foodie'
urlpatterns=[
    path('biryani/',biryani,name='biryani')
]

ola/urls.py
from django.contrib import admin
from django.urls import path,include
import food,travel

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('travel/',include('travel.urls')),
]

travel/urls.py
from django.urls import path
from  travel.views import *
app_name='traveller'
urlpatterns=[
    path('hyderabad/',hyderabad,name='hyderabad')
]

food/models.py
from django.db import models

# Create your models here.

travel/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.
def biryani(request):
    return render(request,'biryani.html')

travel/views.py
from django.shortcuts import render

# Create your views here.
def hyderabad(request):
    return render(request,'hyderabad.html')

templates/biryani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<center>>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            Hyderabad biryani is the best biryani
            
        </h1>
        <h1><a href="{% url 'traveller:hyderabad' %}"> GO to travel </a></h1>
       
    </center>
</body>
</html>

templates/hyderabad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Hyderabad</h1>
        <h1><a href="{% url 'foodie:biryani' %}">GO back to biryani</a></h1>
    </center>
</body>
</html>